### ISSUE TITLE
程序卡住

### ISSUE THREAD

**Issue by 1derian** [nex121/ThinkphpGUI#1]
![image](https://github.com/nex121/ThinkphpGUI/assets/64243067/f487a767-9029-4e28-b270-1901a462b0c0)

一直卡在这里, 不知道什么情况

**Comment by nex121** [comment]
java -jar启动下，看看报错信息。

**Comment by nex121** [comment]
如果是网络不通，返回结果的时间会很长。

**Comment by 1derian** [comment]
![image](https://github.com/nex121/ThinkphpGUI/assets/64243067/ef2ae9ac-cdd0-498c-9f41-7351d1207341)
无报错信息, 会不会是因为打包的问题? jdk1.8

**Comment by 1derian** [comment]
> 

排除了不是网络问题

**Comment by nex121** [comment]
![image](https://github.com/nex121/ThinkphpGUI/assets/29255605/8c24f7da-2dd1-4ac6-9f27-fa34a8d1fa76)
我本地测试没有问题

**Comment by 1derian** [comment]
那师傅能在仓库传一下打包好的jar包吗?

**Comment by 1derian** [comment]
ok了, 是我没打包好, 谢谢师傅

![image](https://github.com/nex121/ThinkphpGUI/assets/64243067/8a09806a-6531-41c5-a31c-f9255de1af01)
