### ISSUE TITLE
可以加微信交流吗

### ISSUE THREAD

**Issue by N0o01** [nex121/ThinkphpGUI#3]
可以加微信交流吗可以加微信交流吗可以加微信交流吗可以加微信交流吗可以加微信交流吗可以加微信交流吗可以加微信交流吗可以加微信交流吗

**Comment by nex121** [comment]
![微信图片_20231023144041](https://github.com/nex121/ThinkphpGUI/assets/29255605/89526d03-9291-4fe5-ae77-04aa7c6f661a)
